set dotenv-load 
duckdb_database := env("DUCKDB_DATABASE")

_default:
    @just --list --unsorted

# Start the Dagster dev server
start:
    uv run dg dev

# Check Dagster definitions
@check:
    uv run dg check defs

# Scaffold a Dagster entity. E.g. scaffold defs dagster.asset/trips.py
@scaffold *args:
    uv run dg scaffold {{args}}

# Materialize an asset
@materialize +args:
    uv run dg launch --assets {{args}}

# Show tables in DuckDB
show-tables:
    #!/usr/bin/env -S uv run --script
    import duckdb
    conn = duckdb.connect(database="{{duckdb_database}}")
    reesults = conn.execute("SHOW TABLES;").fetchall()
    print(reesults)

# Verify table has data
verify-table +table_name:
    #!/usr/bin/env -S uv run --script
    import duckdb
    conn = duckdb.connect(database="{{duckdb_database}}")
    reesults = conn.execute("SELECT count(*) FROM {{table_name}};").fetchall()
    print(reesults)