_default:
    @just --list --unsorted

# Start the Dagster dev server
start:
    uv run dg dev

# Check Dagster definitions
@check:
    uv run dg check defs

# Scaffold a Dagster entity. E.g. scaffold defs dagster.asset/trips.py
@scaffold *args:
    uv run dg scaffold {{args}}

# Materialize an asset
@materialize +args:
    uv run dg launch --assets {{args}}