_default:
    @just --list --unsorted

# Start the Dagster dev server
start:
    uv run dg dev

# Check Dagster definitions
@check:
    uv run dg check defs

# Materialize an asset
@materialize +args:
    uv run dg launch --assets {{args}}